apiVersion: apps/v1
kind: Deployment
metadata:
  name: aic-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aic
      tier: web
  template:
    metadata:
      labels:
        app: aic
        tier: web
    spec:
      containers:
      - name: nidotiate-container
        image: bhoisuvarna/movie
        ports:
        - containerPort: 8090
        resources:
          limits:
            cpu: 400m
            memory: 200Mi
      - name: spring-container
        image: bhoisuvarna/insurancedomain
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 400m
            memory: 200Mi

---
