apiVersion: v1
kind: Service
metadata:
  name: ais-service
spec:
    ports:
      - protocol: TCP
        port: 8090
        targetPort: 8090
    type: NodePort
    selector:
      app: ais
      tier: web    
    ports:
      - protocol: TCP
        port: 8081
        targetPort: 8082
    type: NodePort
    selector:
      app: ais
      tier: web

---
