apiVersion: v1
kind: Service
metadata:
  name: insure-service
spec:
    ports:
      - protocol: TCP
        port: 8090
        targetPort: 8090
    type: NodePort
    selector:
      app: insure
      tier: web    
    ports:
      - protocol: TCP
        port: 8081
        targetPort: 8081
    type: NodePort
    selector:
      app: insure
      tier: web

---
